name: brew pr-pull
on:
  workflow_run:
    workflows:
      - brew test-bot
    types:
      - completed

jobs:
  pr-pull:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download bottles from the test-bot workflow
        uses: actions/download-artifact@v4
        with:
          pattern: bottles*
          merge-multiple: true
          path: bottles
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload bottles to GitHub Packages
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          cd bottles
          brew pr-pull --debug --warn-on-upload-failure "$PR_NUMBER" --tap="$GITHUB_REPOSITORY" --root-url="https://ghcr.io/v2/$GITHUB_REPOSITORY"
